In [1]:
import numpy as np

In [3]:
# initializing one dimensional array

n1=np.array([12,23,45])
n1

array([12, 23, 45])

In [5]:
# initializing multidimensional array
n1=np.array([[12,23,45],[0,4,2,],[5,13,56]])
n1



array([[12, 23, 45],
       [ 0,  4,  2],
       [ 5, 13, 56]])

In [12]:
# initializing array with zeors

n1= np.zeros((2,2))

n1

array([[0., 0.],
       [0., 0.]])

In [13]:
# initializing array with different values

n1=np.full((2,3),56)
n1


array([[56, 56, 56],
       [56, 56, 56]])

In [14]:
# initializing array within range
n1=np.arange(12,23)
n1


array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [17]:
# initializing array with random values

n1=np.random.randint(2,6,100)
n1

array([4, 5, 3, 5, 4, 4, 4, 4, 5, 3, 5, 5, 5, 2, 3, 2, 4, 5, 4, 4, 2, 2,
       5, 3, 3, 5, 4, 2, 2, 3, 3, 4, 3, 5, 4, 3, 5, 5, 4, 4, 2, 5, 5, 4,
       2, 4, 2, 4, 5, 5, 3, 2, 4, 5, 5, 4, 4, 2, 5, 3, 5, 4, 4, 5, 3, 4,
       2, 4, 2, 3, 3, 2, 3, 4, 4, 5, 4, 4, 5, 3, 3, 2, 4, 3, 3, 2, 5, 4,
       3, 3, 4, 4, 2, 5, 3, 2, 3, 2, 3, 4])

# Operations on Numpy

In [18]:
n1=np.array([[12,23,45],[0,4,2,],[5,13,56]])
n1.shape



(3, 3)

In [19]:
n1=np.array([[12,34,56],[145,7,8]])
n2=np.array([[11,35,6],[45,67,89]])
np.vstack((n1,n2))

array([[ 12,  34,  56],
       [145,   7,   8],
       [ 11,  35,   6],
       [ 45,  67,  89]])

In [20]:
n1=np.array([[12,34,56],[145,7,8]])
n2=np.array([[11,35,6],[45,67,89]])
np.hstack((n1,n2))

array([[ 12,  34,  56,  11,  35,   6],
       [145,   7,   8,  45,  67,  89]])

In [24]:
n1=np.array([[12,34,56],[145,7,8]])
n2=np.array([[11,35,6],[45,67,89]])
np.column_stack((n1,n2))

array([[ 12,  34,  56,  11,  35,   6],
       [145,   7,   8,  45,  67,  89]])

In [27]:
n1=np.array([12,34,56])
n2=np.array([11,34,6])
np.intersect1d(n1,n2)

array([34])

In [28]:
n1=np.array([12,34,56])
n2=np.array([11,34,6])
np.setdiff1d(n1,n2)

array([12, 56])

# Numpy Mathematics

In [33]:
n1=np.array([12,34,56])
n2=np.array([11,34,6])
np.sum([n1,n2])

153

In [34]:
n1=np.array([12,34,56])
n2=np.array([11,34,6])
np.sum([n1,n2],axis=0)

array([23, 68, 62])

In [35]:
n1=np.array([12,34,56])
n2=np.array([11,34,6])
np.sum([n1,n2],axis=1)

array([102,  51])

In [37]:
n1=np.array([12,34,56])
n1=n1+100
n1

array([112, 134, 156])

In [38]:
n1=np.array([12,34,56])
n1=n1-100
n1

array([-88, -66, -44])

In [39]:
n1=np.array([12,34,56])
n1=n1*100
n1

array([1200, 3400, 5600])

In [40]:
n1=np.array([12,34,56])
n1=n1/100
n1

array([0.12, 0.34, 0.56])

In [42]:
n1=np.array([12,34,56])
np.mean(n1)

34.0

In [45]:
n1=np.array([12,34,56])
np.std(n1)

17.962924780409974

# Numpy Matrix

In [51]:
n1=np.array([[12,34,56],[1,4,6],[3,8,0]])
n1[0]

array([12, 34, 56])

In [52]:
n1[:]

array([[12, 34, 56],
       [ 1,  4,  6],
       [ 3,  8,  0]])

In [53]:
n1[0:1]

array([[12, 34, 56]])

In [54]:
n1[0:,2]

array([56,  6,  0])

In [55]:
np.transpose(n1)

array([[12,  1,  3],
       [34,  4,  8],
       [56,  6,  0]])

In [56]:
n1=np.array([[12,34,56],[1,4,6],[3,8,0]])
n2=np.array([[12,34,56],[1,4,6],[3,8,0]])
n1.dot(n2)

array([[346, 992, 876],
       [ 34,  98,  80],
       [ 44, 134, 216]])

In [57]:
n1=np.array([[12,34,56],[1,4,6],[3,8,0]])
n2=np.array([[12,34,56],[1,4,6],[3,8,0]])
n2.dot(n1)

array([[346, 992, 876],
       [ 34,  98,  80],
       [ 44, 134, 216]])